#!/usr/bin/env python3
"""Cache baseline/adapted states on trajectories generated by the adapted condition."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

import torch
from safetensors.torch import save_file

from prompt_optimization.civil_comments import read_jsonl, sha256_directory, sha256_file
from prompt_optimization.conditions import decoder_layers, load_condition, render_prompt
from prompt_optimization.teacher_forcing import (
    TeacherForcingExample,
    left_pad_teacher_forcing,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-name", default="google/gemma-2-2b-it")
    parser.add_argument("--model-revision")
    parser.add_argument("--baseline-prompt-template", type=Path, required=True)
    parser.add_argument("--baseline-adapter-path", type=Path)
    parser.add_argument("--adapted-prompt-template", type=Path, required=True)
    parser.add_argument("--adapted-adapter-path", type=Path)
    parser.add_argument("--condition-name", required=True)
    parser.add_argument("--labels", nargs="+", required=True)
    parser.add_argument("--train-file", type=Path, required=True)
    parser.add_argument("--val-file", type=Path, required=True)
    parser.add_argument("--test-file", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--max-input-length", type=int, default=512)
    parser.add_argument("--max-new-tokens", type=int, default=48)
    parser.add_argument("--local-files-only", action="store_true")
    parser.add_argument("--limit", type=int)
    return parser.parse_args()


def write_json(path: Path, payload: Any) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def unique_disjoint(rows: dict[str, list[dict[str, Any]]]) -> None:
    seen: set[str] = set()
    for split, values in rows.items():
        ids = [str(row["id"]) for row in values]
        if len(ids) != len(set(ids)):
            raise ValueError(f"Duplicate IDs in {split}")
        if seen.intersection(ids):
            raise ValueError(f"Split {split} overlaps a preceding split")
        seen.update(ids)


@torch.inference_mode()
def generate_teacher(loaded, rows, max_input_length: int, max_new_tokens: int):
    prompts = [render_prompt(loaded.tokenizer, loaded.prompt_template, str(row["text"])) for row in rows]
    tokenizer = loaded.tokenizer
    tokenizer.padding_side = "left"
    encoded = tokenizer(
        prompts,
        add_special_tokens=False,
        padding=True,
        truncation=True,
        max_length=max_input_length,
        return_tensors="pt",
    ).to(loaded.model.device)
    generated = loaded.model.generate(
        **encoded,
        do_sample=False,
        use_cache=True,
        max_new_tokens=max_new_tokens,
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=tokenizer.eos_token_id,
    )
    continuation = generated[:, encoded.input_ids.shape[1] :]
    result = []
    for token_ids in continuation:
        values = token_ids.tolist()
        if tokenizer.eos_token_id in values:
            values = values[: values.index(tokenizer.eos_token_id) + 1]
        result.append(values)
    return result


@torch.inference_mode()
def capture_on_shared_tokens(loaded, rows, token_rows, max_input_length: int):
    examples = []
    for row, targets in zip(rows, token_rows, strict=True):
        prompt_ids = loaded.tokenizer(
            render_prompt(loaded.tokenizer, loaded.prompt_template, str(row["text"])),
            add_special_tokens=False,
        )["input_ids"]
        if not targets:
            raise ValueError("Adapted generation produced an empty continuation")
        if len(targets) >= max_input_length:
            targets = targets[: max_input_length - 1]
        prompt_ids = prompt_ids[-(max_input_length - len(targets)) :]
        inputs = prompt_ids + targets[:-1]
        start = len(prompt_ids) - 1
        examples.append(
            TeacherForcingExample(
                tuple(inputs), tuple(targets), tuple(range(start, start + len(targets)))
            )
        )
    input_ids, attention_mask, positions, targets = left_pad_teacher_forcing(
        examples, loaded.tokenizer.pad_token_id
    )
    captured: list[torch.Tensor] = []

    def hook(_module: Any, _inputs: Any, output: Any) -> None:
        value = output[0] if isinstance(output, tuple) else output
        captured.append(value.detach())

    handle = decoder_layers(loaded.model)[-1].register_forward_hook(hook)
    try:
        loaded.model(
            input_ids=input_ids.to(loaded.model.device),
            attention_mask=attention_mask.to(loaded.model.device),
            use_cache=False,
            return_dict=True,
        )
    finally:
        handle.remove()
    if len(captured) != 1:
        raise RuntimeError("Final decoder-block hook did not run exactly once")
    final_states = captured[0]
    selected = []
    for index, current in enumerate(positions):
        current = current + loaded.hidden_state_offset
        selected.append(final_states[index, current.to(final_states.device)].to(torch.bfloat16).cpu())
    return selected, targets


def adapter_hash(path: Path | None) -> str | None:
    return sha256_directory(path) if path is not None else None


@torch.inference_mode()
def main() -> None:
    args = parse_args()
    if args.output_dir.exists():
        raise FileExistsError(f"Refusing to overwrite {args.output_dir}")
    visible = os.environ.get("CUDA_VISIBLE_DEVICES", "")
    if not visible or "," in visible:
        raise RuntimeError("Expose exactly one GPU with CUDA_VISIBLE_DEVICES")
    rows = {
        "train": read_jsonl(args.train_file),
        "val": read_jsonl(args.val_file),
        "test": read_jsonl(args.test_file),
    }
    if args.limit is not None:
        rows = {name: values[: args.limit] for name, values in rows.items()}
    unique_disjoint(rows)
    baseline = load_condition(
        model_name=args.model_name,
        model_revision=args.model_revision,
        prompt_template=args.baseline_prompt_template,
        adapter_path=args.baseline_adapter_path,
        local_files_only=args.local_files_only,
    )
    adapted = load_condition(
        model_name=args.model_name,
        model_revision=args.model_revision,
        prompt_template=args.adapted_prompt_template,
        adapter_path=args.adapted_adapter_path,
        local_files_only=args.local_files_only,
    )
    if len(decoder_layers(baseline.model)) != len(decoder_layers(adapted.model)):
        raise ValueError("Baseline and adapted conditions have different decoder depths")
    args.output_dir.mkdir(parents=True)
    contract: dict[str, Any] = {
        "status": "running",
        "condition_name": args.condition_name,
        "model_name": args.model_name,
        "model_revision": args.model_revision,
        "labels": list(args.labels),
        "block": len(decoder_layers(baseline.model)) - 1,
        "baseline": {
            "condition_type": baseline.condition_type,
            "prompt_sha256": sha256_file(args.baseline_prompt_template),
            "adapter_sha256": adapter_hash(args.baseline_adapter_path),
        },
        "adapted": {
            "condition_type": adapted.condition_type,
            "prompt_sha256": sha256_file(args.adapted_prompt_template),
            "adapter_sha256": adapter_hash(args.adapted_adapter_path),
        },
        "splits": {},
    }
    for split, split_rows in rows.items():
        baseline_chunks, adapted_chunks = [], []
        token_chunks, row_indices, step_indices = [], [], []
        offsets = [0]
        generated_texts = []
        for start in range(0, len(split_rows), args.batch_size):
            batch = split_rows[start : start + args.batch_size]
            token_rows = generate_teacher(
                adapted, batch, args.max_input_length, args.max_new_tokens
            )
            baseline_states, baseline_targets = capture_on_shared_tokens(
                baseline, batch, token_rows, args.max_input_length
            )
            adapted_states, adapted_targets = capture_on_shared_tokens(
                adapted, batch, token_rows, args.max_input_length
            )
            for local, (base_values, target_values, base_tokens, target_tokens) in enumerate(
                zip(
                    baseline_states,
                    adapted_states,
                    baseline_targets,
                    adapted_targets,
                    strict=True,
                )
            ):
                if not torch.equal(base_tokens, target_tokens):
                    raise RuntimeError("Teacher-forced token targets diverged")
                baseline_chunks.append(base_values)
                adapted_chunks.append(target_values)
                token_chunks.append(base_tokens)
                row_indices.append(torch.full((len(base_tokens),), start + local, dtype=torch.int32))
                step_indices.append(torch.arange(len(base_tokens), dtype=torch.int16))
                offsets.append(offsets[-1] + len(base_tokens))
                generated_texts.append(
                    adapted.tokenizer.decode(base_tokens.tolist(), skip_special_tokens=True)
                )
        payload = {
            "baseline": torch.cat(baseline_chunks).contiguous(),
            "adapted": torch.cat(adapted_chunks).contiguous(),
            "token_ids": torch.cat(token_chunks).long().contiguous(),
            "row_index": torch.cat(row_indices).contiguous(),
            "step_index": torch.cat(step_indices).contiguous(),
            "offsets": torch.tensor(offsets, dtype=torch.int64),
        }
        path = args.output_dir / f"{split}.safetensors"
        save_file(payload, str(path))
        records_path = args.output_dir / f"{split}_teacher_records.jsonl"
        records_path.write_text(
            "".join(
                json.dumps(
                    {
                        "id": str(row["id"]),
                        "gold": row.get("labels"),
                        "generated_text": text,
                    },
                    ensure_ascii=False,
                )
                + "\n"
                for row, text in zip(split_rows, generated_texts, strict=True)
            ),
            encoding="utf-8",
        )
        source_file = {"train": args.train_file, "val": args.val_file, "test": args.test_file}[split]
        contract["splits"][split] = {
            "path": path.name,
            "sha256": sha256_file(path),
            "source_path": str(source_file.resolve()),
            "source_sha256": sha256_file(source_file),
            "rows": len(split_rows),
            "positions": len(payload["token_ids"]),
            "ids": [str(row["id"]) for row in split_rows],
        }
    contract["status"] = "done"
    write_json(args.output_dir / "contract.json", contract)


if __name__ == "__main__":
    main()
