#!/usr/bin/env python3
"""Score the published unpruned responses with this repo's parser and metric.

The prune-0 cell does not need a GPU: the published ``*.responses.jsonl`` hold
the same 500 examples this sweep runs on, generated by the same arms with no
pruning. Re-scoring them here puts the baseline in the same coordinate system
as the pruned cells - same parser, same NONE policy, same metric - which is the
only way the deltas mean anything.

What it cannot fix: those responses came from a different harness run. The
comparison is like-for-like on scoring, not on decoding.

    uv run scripts/baseline_from_published.py --dir routing_data --out results/baseline_prune000
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Sequence

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from mrd_pruning.task import f1_sample, parse_response, predicted_labels, score_batch  # noqa: E402

logger = logging.getLogger("baseline")

# cell file -> (arm name, response field in that file)
CELLS = {
    "frozen_base": ("base", "base_response"),
    "frozen_gepa": ("gepa", "gepa_response"),
    "frozen_pt": ("prompt_tuning", "prompt_tuning_response"),
    "frozen_prefix": ("prefix_tuning", "prefix_tuning_response"),
}


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dir", required=True, type=Path, help="directory with *.responses.jsonl")
    p.add_argument("--out", required=True, type=Path)
    p.add_argument("--none-policy", default="lenient", choices=["lenient", "strict"])
    return p.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    args = parse_args(argv)
    args.out.mkdir(parents=True, exist_ok=True)
    index: list[dict] = []

    for cell, (arm, field) in CELLS.items():
        path = args.dir / f"{cell}.responses.jsonl"
        if not path.exists():
            logger.warning("%s missing, skipping %s", path.name, arm)
            continue
        rows = [json.loads(line) for line in path.read_text().splitlines() if line.strip()]
        summary, scored = score_batch(
            (row[field] for row in rows),
            (row["gold"] for row in rows),
            none_policy=args.none_policy,
        )

        # The published *_score used the strict rule; reproducing it exactly is
        # the check that this parser is the same one, not a lookalike.
        published_key = field.replace("_response", "_score")
        n_diff = sum(
            1 for row in rows
            if abs(f1_sample(predicted_labels(parse_response(row[field]), "strict"), row["gold"])
                   - row[published_key]) > 1e-9
        )
        published_mean = sum(row[published_key] for row in rows) / len(rows)

        record = {
            "arm": arm,
            "prune_level": 0,
            "prune_level_pct": 0.0,
            "source": f"published:{path.name}:{field}",
            "none_policy": args.none_policy,
            "published_f1_mean": round(published_mean, 6),
            "strict_rescore_mismatches": n_diff,
            **summary.as_dict(),
        }
        index.append(record)
        cell_dir = args.out / f"{arm}_prune000"
        cell_dir.mkdir(parents=True, exist_ok=True)
        (cell_dir / "summary.json").write_text(json.dumps(record, indent=2, ensure_ascii=False))
        with (cell_dir / "results.jsonl").open("w") as handle:
            for row in scored:
                handle.write(json.dumps(row, ensure_ascii=False) + "\n")
        logger.info(
            "%-14s F1 %.4f (published %.4f, strict mismatches %d) | empty %.1f%% | unparsable %.1f%%",
            arm, summary.f1_mean, published_mean, n_diff,
            100 * summary.empty_pred_rate, 100 * summary.unparsable_rate,
        )

    if not index:
        raise SystemExit("no response files found")
    (args.out / "index.json").write_text(json.dumps(index, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
